FROM node:22-alpine AS base
# If you're using M1, M2 Mac, try this: 
# FROM  --platform=linux/amd64 node:16.14.0-alpine

# Set the working directory
WORKDIR /usr/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application files
COPY . .

# Expose the port
EXPOSE 3002

ENV NEXT_TELEMETRY_DISABLED=1





# Start the application
CMD ["npm", "run" , "dev"]